apiVersion: v1
kind: Service
metadata:
  name: sc-vote
  labels:
    app: servicecraze
    tier: frontend
spec:
  # Use this if using Ingress for LB
  type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
#  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8090
  selector:
    app: sc-vote
    tier: frontend
